version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql-docker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Wertzu_86
      MYSQL_DATABASE: productdb_docker
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    image: employee-image
    container_name: employee-container
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/productdb_docker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Wertzu_86
    restart: on-failure

  frontend:
    build:
      context: ../employeeweb
      dockerfile: Dockerfile
    image: react-ui-docker
    container_name: react-container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: on-failure



volumes:
  mysql-data:
